### ISSUE TITLE
Add possibility to subscribe with date restriction

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#10]
I see the main use case as following:

- I already made some appointment booking for 2+ months in the future
- So in general, there *are* available appointments, but not really soon
- As a bot user, I want to find some appointment which is earlier (i.e. for tomorrow).

So it would be nice to have possibility to restrict date like "send me notifications only if available termin is before than 01-01-2020"

**Comment by faye-tan** [comment]
I would like to work on this issue!

**Comment by okainov** [comment]
Fixed with #39 and #70, thanks @aestuans for contribution!
