### ISSUE TITLE
Add link to booking website

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#11]
As #4 is not implemented yet, it would be nice to at least have a direct link "go book here" together with results

**Comment by guipsamora** [comment]
I am going to try adding the link for booking

**Comment by okainov** [comment]
@guipsamora cool, welcome!

**Comment by guipsamora** [comment]
@okainov I just submitted a PR, please review it and change whatever is needed to improve it. At first I wanted to make it very specific, taking the appointment type into consideration but it would make it much more complex. So I am simply redirecting the user to the generic appointment website of the respective Büro.
