### ISSUE TITLE
Add support for other documents

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#2]
Except of driver license, there are online termins in other gov. places using very similar termin system:

Department of motor vehicles (Fuhrerscheinstelle) https://www.muenchen.de/rathaus/terminvereinbarung_fs.html <- The one currently supported
Burger buro (i.e. Anmeldung) main page https://www.muenchen.de/rathaus/terminvereinbarung_bb.html and frame https://www56.muenchen.de/termin/index.php?loc=BB
NE with Blue Card http://www.muenchen.de/dienstleistungsfinder/muenchen/1080805/ - potentially covered in https://github.com/aqeelarshad19/munich-scripts, @aqeelarshad19 would you like to collaborate here?
Maybe some others

**Comment by okainov** [comment]
Mostly fixed in 86a3ebff93ba4cbf463a584ded1d7598b78e38d9 and 55630b5aa82695cb826332de8b83da1ab18da637

**Comment by aqeelarshad19** [comment]
You have already added the support for the NE with Blue Card, :+1: . In my repo, I have also added an extra link to check if the NE card us ready to be picked up from the KVR. 
I also like the feature with the TG chat bot.
