### ISSUE TITLE
Subscription is lost after ~1.5 days

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#20]
For some reason seems like subscription gets cancelled after ~1.5 days instead of 7. Need to double-check and debug

**Comment by guipsamora** [comment]
@okainov  out of curiosity, how do you know that subscriptions are getting cancelled?

**Comment by okainov** [comment]
I add subscription for myself and then check logs =) That's why I have Kibana dashboard. 

Just run some subscription now, will check tomorrow and attach the screenshot :)

**Comment by guipsamora** [comment]
Cool, thanks for letting me know. Could you help me set this up as well? I would like to work more on this project.

**Comment by okainov** [comment]
![image](https://user-images.githubusercontent.com/918446/70266641-2ff34d80-179d-11ea-9e53-076e325dfc35.png)

Here are some of my logs last days. We can see, it's just lost after several hours

I'll try to update README with some of ELK setup steps, but also you should be able to see normal print logs if you have it running somewhere on your server

**Comment by okainov** [comment]
He-he, seems like it's because of Heroku's "[cycling](https://devcenter.heroku.com/articles/dynos#automatic-dyno-restarts)". And since it happens in a random timeframe and not displayed in the log, that's why it was so complicated to find out.

Yet another reason to finally migrate to the separated server, also will help in #14
