### ISSUE TITLE
Aufenthaltserlaubnis Blaue Karte EU

### ISSUE THREAD

**Issue by mazdack** [okainov/munich-scripts#24]
Seems like appointment title <Aufenthaltserlaubnis Blaue Karte EU> is not accepted by the buro <Ausländerbehörde> any more

**Comment by okainov** [comment]
Could you please add more details? Just checked - seems fine

![image](https://user-images.githubusercontent.com/918446/70718024-c2d93e00-1cef-11ea-96bd-802908d31968.png)

**Comment by mazdack** [comment]
![image](https://user-images.githubusercontent.com/6659876/70718289-3b3fff00-1cf0-11ea-8990-468ff3042122.png)
yeap, seems ok now, just got an error message earlier

**Comment by mazdack** [comment]
![image](https://user-images.githubusercontent.com/6659876/70984661-2a5e0780-20bb-11ea-8243-9968c53e8077.png)
i continue to get this message

**Comment by amrzahran123** [comment]
@okainov Unfortunately I am getting the same error in the screenshot above. It is sad that when I finally needed to use the bot it is not working anymore! :D

**Comment by okainov** [comment]
@amrzahran123 Just noticed also, working on it. First change was that KVR changed their URLs (now it's `https://www22.muenchen.de/view-fs/termin/` and similar) and second I still not sure, trying out now...

**Comment by okainov** [comment]
@amrzahran123 please check now, seems fixed. Sorry for inconvenience, this time it was really caused by KVR-side change.
