### ISSUE TITLE
Error in service title: Aufenthaltserlaubnis Blaue Karte EU 

### ISSUE THREAD

**Issue by tatarintseva** [okainov/munich-scripts#32]
I created a subscription with details: 

 - Department: Ausländerbehörde 
 - Type: Aufenthaltserlaubnis Blaue Karte EU 
 - Interval: 0:10:00 
 - Until: 19-02-2020 19:56:16

Got an error: 
Seems like appointment title <Aufenthaltserlaubnis Blaue Karte EU> is not accepted by the buro <Ausländerbehörde> any more

**Comment by okainov** [comment]
Thanks for the report, will take a look soon

**Comment by okainov** [comment]
Fixed
