### ISSUE TITLE
Please check / re-create script for Niderlassungserlaubnis over 16

### ISSUE THREAD

**Issue by andreikarpov** [okainov/munich-scripts#34]
Please re-create script for Niderlassungserlaubnis over 16. Not working now. This is the start page for it:
https://www.muenchen.de/rathaus/terminvereinbarung_abh.html?cts=1064109
Thanks!

**Comment by okainov** [comment]
Should be back. I used to query ABH page for the available termins, but now they blocked it, so I've rolled back to hardcoded list
