### ISSUE TITLE
No option on booking site

### ISSUE THREAD

**Issue by proua** [okainov/munich-scripts#35]
In bot I see option 'Aufenhaltserlaubnis zur Beschaftigung (Fachkarte / Mengelberufe)', but no option on booking site

**Comment by okainov** [comment]
I'm using the names which their backend uses and it may be different from what they show to users.
In this case, `Aufenthaltserlaubnis zur Beschäftigung (Fachkräfte / Mangelberufe)` corresponds to 
```
Aufenthaltserlaubnis zur Beschäftigung (Akademiker) 
Anzahl der Personen, die einen Aufenthaltstitel beantragen (auch ausländische Ehegatten und Kinder) 
Residence permit for employment (academics) 
Number of persons applying for a residence permit (including foreign spouses and children)
``` 
which can be booked at https://www.muenchen.de/rathaus/terminvereinbarung_/terminvereinbarung_abh.html?cts=10278359

So I see no issue here, thus closing the ticket.
