### ISSUE TITLE
Errors in bot

### ISSUE THREAD

**Issue by Den5i** [okainov/munich-scripts#36]
Seems like appointment title <Aufenthaltserlaubnis Blaue Karte EU> is not accepted by the buro <Ausländerbehörde> any more
Please create issue on Github (https://github.com/okainov/munich-scripts/issues/new)

Current subscription details:

 - Department: Ausländerbehörde 
 - Type: Aufenthaltserlaubnis Blaue Karte EU 
 - Interval: 0:05:00 
 - Until: 08-03-2020 15:25:05

**Comment by okainov** [comment]
Thanks for the report!

Fixed, reason is again ABH tries to improve their security by adding extra validation and bot protection. Infinite battle :)
