### ISSUE TITLE
Ausländerbehörde problem

### ISSUE THREAD

**Issue by ozdemiryucel** [okainov/munich-scripts#37]
I am trying to get Termine Ausländerbehörde for Residence permit to study.

The telegram part sticks after "Fetching available appointment types..." as you can see the picture
https://drive.google.com/file/d/199clrziXmMr4HKZ4JFWy6VWVW0cfevyW/view

And I don't know whether "appointments = get_termins(ForeignLabor, 'Niederlassungserlaubnis allgemein')" line in the termin_api.py works or not. Because I always get "ERROR: cannot find termins data in server\'s response. See log.txt for raw text" message, I put an inifinity loop in main function, but I don't get any appointment messages for 2 days.

**Comment by okainov** [comment]
Thanks for the report!

Should be fixed now. ABH introduced yet another level of check (so far it's easy fixable, but I don't like the trend).
