### ISSUE TITLE
Telegram bot unresponsive after /start

### ISSUE THREAD

**Issue by madhurikulkarni** [okainov/munich-scripts#38]
The telegram bot does not update further options after `/start`. Device used iPhone X and also using a non German number matters ? 
![B2F134E4-7FEC-4EDB-9BD4-05CD99581B9C](https://user-images.githubusercontent.com/18307129/76221254-784d5c00-6221-11ea-9d20-297ac5888cbd.jpeg)

**Comment by okainov** [comment]
Thanks for the report! Fixed!

Apparently I forgot to reload nginx after renewing SSL certificate, so it was reporting as expired :(
