### ISSUE TITLE
Blaue carte appointment error (captcha on web form)

### ISSUE THREAD

**Issue by tatarintseva** [okainov/munich-scripts#40]
Appointments check for Aufenthaltserlaubnis Blaue Karte EU returns an error. 
When checking the website manually I see they implemented captcha on it. Is there any chance to go on with the bot regarding this change?

**Comment by okainov** [comment]
See https://github.com/okainov/munich-scripts/issues/68#issuecomment-1193362270. I'll remove this, now BC is not available for online booking the same way as others, you must follow the steps on the webpage instead. But I'll update the bot to mention this
