### ISSUE TITLE
Bot fails to fetch types of appointments for Führerscheinstelle 

### ISSUE THREAD

**Issue by valbub** [okainov/munich-scripts#63]
Yesterday and today I tried to set an alert for Führerscheinstelle appointments. But the bot freezes on “Fetching available appointment types...”. 

Yesterday, it just printed this once and froze. Today, it keeps repeating this message over and over with no result. 

For other offices it works fine for me.

![Uploading E2A94743-8134-45E1-9676-4326917F5258.png…]()

**Comment by okainov** [comment]
Maybe they have updated something again... I will try to take a look, thanks for reporting!

**Comment by okainov** [comment]
Should be fixed with #64
