### ISSUE TITLE
Seems like appointment title <FS Abholung Führerschein> is not accepted by the buro <Führerscheinstelle> any more

### ISSUE THREAD

**Issue by proshin-roman** [okainov/munich-scripts#65]
The new title seems the following: `Abholung eines Führerscheines`

Also, it can be found on the attached screenshot:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/3031372/159671808-dbaadc13-2e10-4571-835b-e5d729d522a1.png">

**Comment by mohnishjadhav213** [comment]
I am getting the same message. The last option u mentioned is “pickup driver license”and not converting the license. Do you know if this works or any other way to get the appointment?

**Comment by okainov** [comment]
Sorry for long reply


It seems like it's still working. Maybe it was temporary buro's glitch? Feel free to reopen if the issue appears again

BTW I do not rely on the visible title of the termin but on the ID from the source code (the one from array `CASETYPES`).

```
Great, wait a second while I'm fetching available appointments for FS Abholung Führerschein...
The nearest appointments at Führerscheinstelle Garmischer Str. 19/21 are on 2022-07-25:
08:05
11:00
```
