### ISSUE TITLE
Add subscription

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#7]
Would be nice to be able to subscribe for some termin so TG bot could notify you when any termins are available

**Comment by joistick11** [comment]
Hi 
I've done it already and tested on my own bot. I am planning to create a PR in a few days with this functionality.

**Comment by joistick11** [comment]
Here we go https://github.com/okainov/munich-scripts/pull/8

**Comment by okainov** [comment]
Thanks! Merged, deployed, should be available at @MunichTerminBot :)
