### ISSUE TITLE
Outdated Appointment categories

### ISSUE THREAD

**Issue by Kiran-kkt** [okainov/munich-scripts#79]
I was thrilled when I found "Familiennachzug(SCIF)" category for appointments however it turns out to be there is no such category. In fact there aren't many categories available as I think the office (Büro) has updated it's page. Please do fix this issue as this might give a false hope for the people who are trying for a longtime.

**Comment by okainov** [comment]
The names of the appointments are retrieved automatically from the buro webpage. There might be indeed name difference as the data we're showing is coming from Javascript/JSON data and in the UI they might be named a bit differently, but the point is still the same.
Could you please clarify, which buro do you mean? I don't see it for neither KVR, DMV or Burgerburo.

**Comment by Kiran-kkt** [comment]
Sorry, for not mentioning it properly. I meant Ausländerbehorde -> `Class ForeignLabor(Buro)`. They don't offer online appointment booking service any more as mentioned in the code. So I wonder, why is it still shown as one of the departments for appointment booking? I think this should be deprecated, of course, until they reinstate it back or maybe echo the message when the department is selected.

**Comment by okainov** [comment]
>They don't offer online appointment booking service any more as mentioned in the code

That's the trick :)


> So I wonder, why is it still shown as one of the departments for appointment booking? I think this should be deprecated, of course, until they reinstate it back or maybe echo the message when the department is selected.

Because I wanted to avoid questions like "Where is ABH, why don't you support it". That's why I added it with big and noticeable (hopefully) warning message that you should go to the given URL for applying to whatever in ABH. And I don't give any list of any appointments (can you also explain how did you get to the list having the item mentioned?), there is no URLs from where to fetch it from:

>maybe echo the message when the department is selected.

That's exactly what is happening now, isn't it? ;)

![image](https://user-images.githubusercontent.com/918446/198290880-26d4986b-0ac4-49d2-a98c-56c84dbf4ef1.png)

**Comment by kiran-tunuguntla** [comment]
> That's exactly what is happening now, isn't it? ;)

Unfortunately, no this is not what I saw.

I saw this

![IMG_3210](https://user-images.githubusercontent.com/111503866/198319667-410dd23e-b46f-46aa-931c-1b87e98e651b.PNG)
![IMG_3213](https://user-images.githubusercontent.com/111503866/198319690-e9a493a5-603d-4c88-a602-720a1a965944.PNG)
![IMG_3215](https://user-images.githubusercontent.com/111503866/198319711-6d3264f6-cbb9-4260-b94d-3ff26e82fb30.PNG)

**NOTE:** I installed the Telegram app(iOS) yesterday and subscribed to the bot last night. 

By the way, it was the same case with my friend.

Screenshots from his phone(Android).

![WhatsApp Bild 2022-10-27 um 16 35 36](https://user-images.githubusercontent.com/111503866/198320965-788089d4-5bb5-4dc0-8e5d-adcaffa734de.jpg)
![WhatsApp Bild 2022-10-27 um 16 33 26](https://user-images.githubusercontent.com/111503866/198321133-7366c224-6480-4fd0-946b-b2dfd41060be.jpg)
![WhatsApp Bild 2022-10-27 um 16 33 38](https://user-images.githubusercontent.com/111503866/198321149-c056cc0c-18e4-4d38-9d21-524edd90faa1.jpg)

Maybe, it's not deployed yet? or Not sure. what could be the reason.

**Comment by kiran-tunuguntla** [comment]
However, I'm happy that the issue has already been fixed. Cheers 👍 to you and thank you responding to my query :)

**Comment by okainov** [comment]
On your screenshot it's not my Telegram bot. Feel free to contact the owner of the bot you're using. I'm not responsible for any issues with any other scripts and/or forks.

I maintain only my bot hosted at https://t.me/MunichTerminBot

**Comment by Kiran-kkt** [comment]
Interesting, the link there redirected to this repository. Anyways, I'll contact the owner and thanks a lot :)
