### ISSUE TITLE
All buros have added captcha?

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#84]
Looks like now there is captcha not only for ABH, but for other buros as well (tried with Burgerburo)... Last week it was fine, so it seems they've just added it...

Anyone knows any free captcha-solving services? Otherwise, I suppose, there is not much help from the scripts/bot any more...

**Comment by sealtooth** [comment]
I just noticed this too.. Unfortunately I can’t help with the technical stuff, but I did the german thing and sent muenchen.stadt an email asking them to revert this update. It’s a shame that they rather do this than actually implement a notification system themselves. Thank you for developing this, saved me and my friends so much time 💛

**Comment by munichterminesindhard** [comment]
I might have a solution. At TUM we used to use these services many years up to now and we can use partners programs and offers to pay daily small amount for it. Will it be more than 1000 captchas per day in totall?

**Comment by rumpeltux** [comment]
I have a somewhat hacky workaround that requires manually solving the captcha. Still much better than the website…
https://github.com/rumpeltux/munich-scripts/commit/14cdae55f7502a7477366ac7a3652f3e7e8d38de
